[Interface]
# Key for USA
# Bouncing = 2
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = YPIGWXpwRTB4D0glPH8Y43t8HS4/INmyvNlI6+3bzkI=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-FREE#1
PublicKey = gucaLaM/mgJQbHVvnZNtW+1L4Mi7E2mtTMrhS0K4miU=
AllowedIPs = 0.0.0.0/0
Endpoint = 146.70.230.146:51820